### ISSUE TITLE
How does katello-packaging/katello/katello-restore restore from incremental backups?

### ISSUE THREAD

**Issue by itewk** [Katello/katello-packaging#310]
I am reading over https://github.com/Katello/katello-packaging/blob/master/katello/katello-restore and https://github.com/Katello/katello-packaging/blob/master/katello/katello-backup  and wondering how the `katello-restore` script manages to restore from backups made using the `katello-backup --incremental` option.

Looking at the `katello-restore` script I don't see anything in there about trying to find the incremental backups.  To be fare I have never used the `tar --listed-incremental` option before and am basing my knowledge off the docs but it seems when using that option you need to extract each incremental backup in sequence which it does not seem that the `katello-restore` script is doing.

Am I missing something?

**Comment by sean797** [comment]
Have a look at the "Incremental restore" section on http://www.katello.org/docs/3.2/user_guide/backup/

Having it loop so the user can only call it once is a bit tricky because you can could store the backups in any directory & have any number of incremental ones, though feel free to create an REF for it http://projects.theforeman.org/projects/katello/issues/new

**Comment by itewk** [comment]
@sean797 thank you. That is a big help. As you said doing something automatically would be tricky. I think the documentation is sufficient.
